<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.vanillabp.businesscockpit</groupId>
    <artifactId>businesscockpit-process-engine-api-adapter-parent</artifactId>
    <version>0.9.0-SNAPSHOT</version>
  </parent>

  <artifactId>businesscockpit-process-engine-api-adapter-quarkus-parent</artifactId>
  <packaging>pom</packaging>
  <name>VanillaBP Business Cockpit adapter for the Process-Engine-API - Quarkus</name>
  <description>The Quarkus extension registering the Process-Engine-API half of the Business Cockpit extension: a runtime half producing the beans and a deployment half telling Quarkus about them.</description>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>VanillaBP</id>
      <organization>Phactum Softwareentwicklung GmbH</organization>
      <organizationUrl>https://www.phactum.at</organizationUrl>
    </developer>
  </developers>

  <modules>
    <module>runtime</module>
    <module>deployment</module>
  </modules>
</project>
